drop table if exists authors CASCADE;
drop table if exists comments CASCADE;
drop table if exists news CASCADE;
drop table if exists tag_news CASCADE;
drop table if exists tags CASCADE;
create table authors
(
    id               bigint generated by default as identity,
    create_date      timestamp,
    last_update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    name             varchar(255),
    primary key (id)
);
create table comments
(
    id               bigint generated by default as identity,
    content          varchar(255),
    create_date      timestamp,
    last_update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    news_id          bigint,
    primary key (id)
);
create table news
(
    id               bigint generated by default as identity,
    content          varchar(255),
    create_date      timestamp,
    last_update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    title            varchar(255),
    author_id        bigint,
    primary key (id)
);
create table tag_news
(
    tag_id  bigint not null,
    news_id bigint not null
);
create table tags
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
alter table comments
    add constraint FKqx89vg0vuof2ninmn5x5eqau2 foreign key (news_id) references news;
alter table news
    add constraint FKse4kp8hpul3sks7iofw87xor6 foreign key (author_id) references authors;
alter table tag_news
    add constraint FKqw54xwh1h7ietbo4hvqsryu5v foreign key (news_id) references news;
alter table tag_news
    add constraint FKbfnhl1q34pwo0cchjwjq1muq foreign key (tag_id) references tags;